/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    application
    kotlin("jvm") version "1.3.40"
}

repositories {
    // Use jcenter for resolving your dependencies.
    jcenter()
    mavenCentral()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    compile(kotlin("stdlib"))

    // Use the Exposed ORM library.
    implementation("org.jetbrains.exposed:exposed:0.14.4")
    compile("org.jetbrains.exposed:exposed:0.14.4")

    // Use the PostgreSQL driver library.
    implementation("org.postgresql:postgresql:42.2.2")
    compile("org.postgresql:postgresql:42.2.2")

    implementation("org.slf4j:slf4j-jdk14:1.7.9")
    compile("org.slf4j:slf4j-jdk14:1.7.9")
    
    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Use Mockk as the mocking library.
    testImplementation("io.mockk:mockk:1.9.3")
}

application {
    // Define the main class for the application.
    mainClassName = "tic_tac_toe.AppKt"
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = application.mainClassName
    }

    from(configurations.runtime.get().map {if (it.isDirectory) it else zipTree(it)})
}
