/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tic_tac_toe

import tic_tac_toe.game_client.GameClient
import tic_tac_toe.game_client.mode.PvP
import tic_tac_toe.game_client.mode.local.LocalMI
import tic_tac_toe.game_client.user_interface.console.ConsoleInput
import tic_tac_toe.game_client.user_interface.console.ConsoleOutput
import tic_tac_toe.game_client.user_interface.console.ConsoleUI
import tic_tac_toe.game_manager.GameManager
import tic_tac_toe.game_manager.repo.PostgresRepo

fun main() {
    val ui = ConsoleUI(ConsoleInput(), ConsoleOutput())
    val gm = GameManager(PostgresRepo())
    val client = GameClient(ui)
    client.start(mapOf("Player vs. Player" to PvP(ui, LocalMI(gm))))
}
